### ISSUE TITLE
If source image is bigger than image size set within UE5.2 it will cause touch issues

### ISSUE THREAD

**Issue by FadyFaheem** [JanSeliv/CustomShapeButton#4]
This isn't really an issue but with larger images, if you don't properly set the resolution it can cause issues with touch input.

![Layer 1CircleCircle](https://github.com/JanSeliv/CustomShapeButton/assets/46271420/c57040c5-ec2d-44be-8163-8f1e6a145a8d)
![Layer 1CircleHoveredCircleCircle](https://github.com/JanSeliv/CustomShapeButton/assets/46271420/650b79d6-6f44-4052-b34a-5a17ce2cd097)
![Layer 1CirclePressedCircleCircle](https://github.com/JanSeliv/CustomShapeButton/assets/46271420/c6bba8d0-f974-4f3a-ac78-fc3f99cb6462)

Here are images that cause this issue.

**Comment by JanSeliv** [comment]
Thank you for clear explanation.
I will try to look at it and investigate what happens with next UE release

**Comment by JanSeliv** [comment]
Hi, @FadyFaheem

I downloaded your images and reproduced the issue on my Android device - the button stays in the Hover state after being pressed. I didn't find any other problems.
- Is this the issue you're talking about? I looked into it and found that the problem comes from the Engine code. Also, when I used your images on a regular Epic's 'Button', the same thing happened.
- Can you try using a regular Epic's 'Button' with your images and see if you get the same issue?

**Comment by FadyFaheem** [comment]
The issue was resolved after correcting the image sizes. These images were scaled to 1024x1024 when exported and then downscaled in UE down to 512x512, causing this issue.

**Comment by JanSeliv** [comment]
Thank you for the update. I'm glad to hear there's a workaround by adjusting the image sizes. Closing this issue now. If Epic addresses this but the problem persists with the plugin, feel free to open a new issue.
